name: Zip examples folder

on:
  workflow_dispatch:
  push:
    paths:
    - 'examples/**'

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: 'examples/'
          filename: 'examples.zip'
#       - uses: papeloto/action-zip@v1
#         with:
#           files: examples/
#           dest: examples.zip

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Archive examples.
