name: Zip examples folder

on:
  workflow_dispatch:
  push:
    paths:
    - 'examples/**'

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: examples/
          dest: examples.zip

      - uses: actions/upload-artifact@v2
        with:
          name: examples
          path: ${{ github.workspace }}/examples.zip
